### ISSUE TITLE
Custom element doesn`t exist: fan-xiaomi

### ISSUE THREAD

**Issue by Doxlike** [ikaruswill/lovelace-fan-xiaomi#106]
Hi,

i try to add your nice looking custom fan card. But its not working. Iam using syssis xiamo_fan integration and added your frontend repo via Hacs but it shows the following error:

![image](https://user-images.githubusercontent.com/2735923/180501951-fa89fb67-0098-4de2-b2a8-cccc700c765c.png)

br 
Doxlike

**Comment by Doxlike** [comment]
Fixed the issue with the beta version 2.2.0

**Comment by Arakon** [comment]
Getting this same issue even with 2.2.1.

**Comment by Draluak** [comment]
> Getting this same issue even with 2.2.1.

same here

**Comment by caoyaochong** [comment]
> > Getting this same issue even with 2.2.1.
> 
> same here

same here too
