### ISSUE TITLE
Mobile interface touch controls opens details view instead

### ISSUE THREAD

**Issue by ikaruswill** [ikaruswill/lovelace-fan-xiaomi#107]
Appears that in 2.2.0, touching anything on the card simply opens the details view.

No such issue with 2.1.0. Using home-assistant `2022.7.4`

**Comment by Rjaap** [comment]
Came here because I noticed the same problem. The update of the card installed without problems but now I get the message that the card is not loaded properly. Restart/reinstall doesn't make a difference.

**Comment by ikaruswill** [comment]
Hmm this is much more involved than I had initially thought. I tested with desktop but I guess I neglected mobile. @ian-craig  any ideas on why this might be happening?

**Comment by ian-craig** [comment]
Just created a PR. @ikaruswill I'll let you take a look and see if this looks reasonable and you can go ahead and merge.

**Comment by ikaruswill** [comment]
Tested and confirmed that it works. Thanks again!

**Comment by Rjaap** [comment]
Works like a charm again. Thanks!
