### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Bastiencc** [ikaruswill/lovelace-fan-xiaomi#110]
Hello

Thanks for your great work! 👍 
Just for information, the installation documentation is not up to date : 

```
- url: /hacsfiles/lovelace-fan-xiaomi/fan-xiaomi.js
  type: module
```
to
```
- url: /hacsfiles/lovelace-fan-xiaomi/xiaomi-fan-card.js
  type: module
```

**Comment by Olegz73** [comment]
Installed latest version via hacs, it's didn't work. Rename like this : Custom element doesn't exist: xiaomi-fan-card.

**Comment by Bastiencc** [comment]
> Installed latest version via hacs, it's didn't work. Rename like this : Custom element doesn't exist: xiaomi-fan-card.

just rename the ressources , not the lovelace card , still use : ` type: 'custom:fan-xiaomi'`
