### ISSUE TITLE
Card not display in dashboard.

### ISSUE THREAD

**Issue by WarC0zes** [ikaruswill/lovelace-fan-xiaomi#111]
Hi,
I installed your card ( v2.2.1) and it does not appear when I use the xiaomi_miio_fan platform.
You can see on the pictures with xiaomi_miio_fan selected or by default.
No error in log.

platform: xiaomi_miio_fan ( if you change the options of the card in UI, the card reappears in the UI. But as soon as we save, it disappears from the dashboard.)
![fan card](https://user-images.githubusercontent.com/91471397/182654783-43f51f62-c3b4-434f-a913-a58e65e8c6e8.png)

platform: default (but not full options working)
![fan card 2](https://user-images.githubusercontent.com/91471397/182654882-a61afbeb-1d99-4ae9-ad5a-e1a79675b576.png)

my fan model is the Mi Smart Standing Fan 2 (dmaker.fan.p18).
HAOS 8.4
Core 2022.8.0
Supervisor 2022.7.0

Is this a glitch?

**Comment by JoachimEngelmann** [comment]
I have the same issue and reverted back to 2.1.0 for now

**Comment by Stimpy68** [comment]
Same here

**Comment by hostrup** [comment]
Same here!

**Comment by yayitazale** [comment]
same

**Comment by MrThiemann** [comment]
I can confirm.. but if I then, for example, open and close a controller (so that I get the "save" field), it is then displayed to me on my dashboard.

**Comment by georgezhao2010** [comment]
Same

**Comment by pltanton** [comment]
Same here!

**Comment by starmaex** [comment]
Me too

**Comment by Stimpy68** [comment]
Seems that this project is dead?

**Comment by Cheerpipe** [comment]
> open and close a controller

Hi @MrThiemann .

¿Could you please elaborate more on this?

Thanks in advance

**Comment by WarC0zes** [comment]
Hi,
@cyberden, thanks for fix, it works.
@ikaruswill , thanks for release. Ready for it's summer :)

I close.
