### ISSUE TITLE
Custom element doesn't exist: fan-xiaomi

### ISSUE THREAD

**Issue by DanielMashraki** [ikaruswill/lovelace-fan-xiaomi#119]
When opening the dashboard from the web or phone app, I get a red box saying "Custom element doesn't exist: fan-xiaomi".

![image](https://user-images.githubusercontent.com/12997061/193516931-19efe3df-cd8f-4d4f-9988-e392eb90f0da.png)

**Comment by xguitoux** [comment]
Hello I'm getting also this error
I'm with 2.2.2 card version

And for Hass
Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.1
Interface utilisateur : 20230503.3 - latest

**Comment by xguitoux** [comment]
Fixed it, file was not loaded as a module in lovelace, don't know why...
