### ISSUE TITLE
Card broken in 0.110.0

### ISSUE THREAD

**Issue by andriej** [ikaruswill/lovelace-fan-xiaomi#14]
In latest HA there's an issue with the card. May be caused by new icon's loading mode in frontend?

![image](https://user-images.githubusercontent.com/6303489/82428313-9d184800-9a8a-11ea-871d-503aaea0bfa8.png)

**Comment by ikaruswill** [comment]
Thanks for flagging this @andriej, I faced it too just yesterday on upgrading. It is now fixed in v1.4. An upgrade should fix things
