### ISSUE TITLE
Unable to turn off timer mode

### ISSUE THREAD

**Issue by ikaruswill** [ikaruswill/lovelace-fan-xiaomi#19]
There's currently no toggle-able state to turn off scheduled turn off.

**Comment by insajd** [comment]
no. work in progress....

**Comment by insajd** [comment]
See this line, https://github.com/syssi/python-miio/blob/1a52117eed74cc81a966df55582fe66be8821490/miio/fan.py#L561
It looks like we can't pass anything that turns timer mode off. We can turn off+on quickly the fan, that should reset the timer. Or, try to propose some changes to python-miio if it's possible to turn off this timer somehow...

**Comment by ikaruswill** [comment]
Yeah no work in progress on this at the moment, I wrote this issue from the angle that we can turn the timer off in the Mi Home App so I thought there shouldn't be a reason why we can't do it with python-miio.

My plan was to understand the code and possibly propose changes to `python-miio`

**Comment by insajd** [comment]
Created PR in https://github.com/rytilahti/python-miio/pull/741 and https://github.com/syssi/xiaomi_fan/pull/70
After they both are merged, this component will be able to disable scheduled turn off by passing 0 as value for delayed turn off.

**Comment by ikaruswill** [comment]
Nice! Thanks for your work on this, @insajd

**Comment by insajd** [comment]
Iimplemented, needs https://github.com/syssi/xiaomi_fan **develop** branch currently. When there's release after 0.2.0, xiaomi fan card release can be released without -beta :)
