### ISSUE TITLE
fan xiaomi.zhimi.fan.v3 ver.1.5

### ISSUE THREAD

**Issue by trx900** [ikaruswill/lovelace-fan-xiaomi#27]
Version 1.5, lost the ability to control speed, causes an error, lost animation. Version 1.4 does not show any such problems.

![image](https://user-images.githubusercontent.com/46130509/82910700-2650e280-9f95-11ea-90ae-d574f68aac43.png)

**Comment by ikaruswill** [comment]
Off the top of my head, I suspect it's a cache issue. 

Funny that the speed icon has errors, there were no changes to the icons used except for swapping out with `ha-icon` and the removal of `Speed Level 5`. I've never seen such red question marks before. 

Perhaps the browser is looking for both the `[5] icon` and the `default animation class` that has since been removed. 

Can you force a refresh? If it doesn't work, if you're in Chrome, disable cache through dev tools and refresh again. If it still doesn't work, do paste the javascript console logs here.

**Comment by trx900** [comment]
These are my questions. I wanted to show the problem, sorry for misleading you

**Comment by ikaruswill** [comment]
I see, no worries. Shocked me a little there.

Anyways, I don't think it's a compatibility issue, definitely frontend.

Could do those for me?

> Can you force a refresh? 
> If it doesn't work, if you're in Chrome, disable cache through dev tools and refresh again. 
> If it still doesn't work, do paste the javascript console logs here.

**Comment by trx900** [comment]
refreshing didn't help

Google Chrome
Последняя версия Google Chrome уже установлена
Версия 83.0.4103.61 (Официальная сборка), (64 бит)
![image](https://user-images.githubusercontent.com/46130509/82921244-5d79c080-9fa2-11ea-8094-24bc4047f83f.png)

**Comment by trx900** [comment]
Below are the errors from the console when you click the speed button

=================================================

mwc-ripple-base.ts:203 Uncaught (in promise) {code: "unknown_error", message: "required key not provided @ data['speed']"}
callService @ mwc-ripple-base.ts:203
async function (async)
callService @ mwc-ripple-base.ts:203
ui.querySelector.onclick @ fan-xiaomi.js:101
mwc-ripple-base.ts:203 Uncaught (in promise) {code: "unknown_error", message: "required key not provided @ data['speed']"}
callService @ mwc-ripple-base.ts:203
async function (async)
callService @ mwc-ripple-base.ts:203
ui.querySelector.onclick @ fan-xiaomi.js:101
mwc-ripple-base.ts:203 Uncaught (in promise) {code: "unknown_error", message: "required key not provided @ data['speed']"}
callService @ mwc-ripple-base.ts:203
async function (async)
callService @ mwc-ripple-base.ts:203
ui.querySelector.onclick @ fan-xiaomi.js:101

**Comment by ikaruswill** [comment]
Thanks for the details, I think I know what the issue is. Will push up a fix for it over the next few days.

**Comment by ikaruswill** [comment]
@trx900 Quick question, what's your xiaomi fan's model number? For example, mine's `zhimi.za4`

**Comment by trx900** [comment]
> @trx900 Quick question, what's your xiaomi fan's model number? For example, mine's `zhimi.za4`

zhimi.fan.v3

**Comment by ikaruswill** [comment]
Are you on 0.2.0 for the [xiaomi fan integration](https://github.com/syssi/xiaomi_fan)?

**Comment by trx900** [comment]
> Are you on 0.2.0 for the [xiaomi fan integration](https://github.com/syssi/xiaomi_fan)?

Yes

![79418405-c272eb80-7fde-11ea-804d-b134562af5a3](https://user-images.githubusercontent.com/46130509/83323506-5f38d200-a289-11ea-83df-ab1384588af1.png)

**Comment by ikaruswill** [comment]
Apologies for the auto-closure of this issue. 

The problem is likely due to a failure to detect the current speed level based on the UI element's value. I was using a hacky string indexing method to get the last character of the speed level, and if the parsing fails for some reason, the new speed (icon and animation) cannot be set. 

I've since changed it to use regex with sensible defaults.

Can you try to update to `1.5.1`? 

If it still doesn't work, let me know what you see in the logs.

**Comment by trx900** [comment]
error

2020-05-30 21:01:01 ERROR (MainThread) [frontend.js.latest.202005195] https://11.12.13.14:8123/hacsfiles/lovelace-fan-xiaomi/fan-xiaomi.js:541:42 Uncaught TypeError: Cannot read property '1' of null

**Comment by ikaruswill** [comment]
Thanks for testing it out. 

Weird, it seems that for some reason, the fan isn't passing a valid value of `speed` to the frontend..

Can you show me your fan's entity attributes in `http://{your_ha_url}/developer-tools/state`?

**Comment by trx900** [comment]
> Thanks for testing it out.
> 
> Weird, it seems that for some reason, the fan isn't passing a valid value of `speed` to the frontend..
> 
> Can you show me your fan's entity attributes in `http://{your_ha_url}/developer-tools/state`?

Please tell me where exactly it can be viewed? I will also remind you that there are no problems in version 1.4.

- platform: xiaomi_miio_fan
    name: xiaomi_smartfan
    host: 192.168.1.205
    token: ххххххх

**Comment by ikaruswill** [comment]
I'm aware that version 1.4 has no issues and I appreciate the fact that we're working together to debug this. 

In version 1.5 I've changed the speed levelling to use the `universal` 'Level X' format that should work for all models, hence I'm quite confused about what inputs the frontend receives from the entity. 

If all else fails I'll revert to the old speed parsing logic, though I hope not.

You can view it under `Developer tools`
![image](https://user-images.githubusercontent.com/10669647/83330893-cd4eba80-a2c4-11ea-8dea-e0113beb17e2.png)

On the States (1st) tab:
![image](https://user-images.githubusercontent.com/10669647/83330901-e3f51180-a2c4-11ea-9219-eef08b47c2e2.png)

**Comment by trx900** [comment]
Ok!:_)

![image](https://user-images.githubusercontent.com/46130509/83331044-af318c00-a2bd-11ea-9bbf-1c38ba6f4edb.png)

**Comment by ikaruswill** [comment]
![image](https://user-images.githubusercontent.com/10669647/83332013-70a2ce00-a2cb-11ea-802e-833ac4f62e78.png)

It's weird we both have somewhat different attributes. For example, `speed` in your case is a number while in my case it's a string. 

And you have an additional attribute called `speed_level` which stores the same value as my `speed`.

I'm not sure what else could have gone wrong that has resulted in the `Xiaomi Mi Smart Fan Integration` picking up other attributes from `python_miio`.

Nonetheless, I'll push a fix to use `speed_level` as fallback when `speed` contains only numbers, that should solve it.

**Comment by trx900** [comment]
You didn't change anything in version 1.5.1? I restarted my home assistant and don't see any errors! I'll keep an eye on it if it's OK to unsubscribe.

**Comment by ikaruswill** [comment]
I cleaned up the code and improved error handling in 1.5.1 with default states.

Maybe all it needed was a restart? There must have been some intermittent problems with the `Xiaomi Mi Smart Fan Integration` and `python_miio`. Let me know how it goes!

**Comment by trx900** [comment]
Good afternoon. I don't see any more problems with the map, I think the problem is over.
Thanks!

**Comment by trx900** [comment]
Decided

**Comment by ikaruswill** [comment]
Glad it's working for you @trx900. Take care!
