### ISSUE TITLE
Multiple Fans: Angle function applies to all fans

### ISSUE THREAD

**Issue by matsube11** [ikaruswill/lovelace-fan-xiaomi#31]
v1.5.1

I've got 2 Xiaomi fans `zhimi.fan.za4` and `zhimi.fan.sa1`

Both controlled using this fine lovelace card, but all controls being good, only one is giving me problems, if I click on the `Angle(°)` on any of the fans, both are starting to oscillate and same angle value is set for both fans. However if I click on the `Oscillate` function, it applies only to the selected fan.
Again if all functions are working fine for each individual fan, the `Angle(°)` function applies to all my all fans.

<img width="492" alt="Capture d’écran 2020-06-12 à 23 36 33" src="https://user-images.githubusercontent.com/25221643/84548427-dc425d80-ad05-11ea-99cf-4451b422976e.png">

**Comment by insajd** [comment]
I am not sure that's fixing it, but I know it doesn't break my current fan. WOuld be cool if you could test this fix from https://github.com/ikaruswill/lovelace-fan-xiaomi/pull/32

**Comment by insajd** [comment]
@ikaruswill not sure how to create a beta release (to allow installation via HACS though beta mode). Currently only way to test pull request/branch is to manually merge changes if i'm correct?

**Comment by matsube11** [comment]
Hi,
Thanks @insajd 

I edited directly your changes on my HACS installed `fan-xiaomi.js` but it appears to not fix it, still same behavior.

**Comment by ikaruswill** [comment]
Thanks for looking into this, @insajd.

> @ikaruswill not sure how to create a beta release (to allow installation via HACS though beta mode). Currently only way to test pull request/branch is to manually merge changes if i'm correct?

I was doing that, but I think I've found how to do it with beta releases.

We can tag a commit on any branch and suffix it with anything like `-betaX` where `X` can be a number, create a release and check the box on pre-release, and HACs will pick it up. The release can be on any branch it seems. My experiment results are in the [releases page](https://github.com/ikaruswill/lovelace-fan-xiaomi/releases), will clean them up soon.

Back to the main issue at hand, @insajd I'll tag your branch as `1.5.2-beta1` and draft a pre-release. 

@matsube11  Could you test it by going to HACS, clicking Reinstall, and switch on `Show beta versions`, and install `1.5.2-beta1`, then let us know if that has solved your problem.

**Comment by insajd** [comment]
> Hi,
> Thanks @insajd
> 
> I edited directly your changes on my HACS installed `fan-xiaomi.js` but it appears to not fix it, still same behavior.

When editing directly, you must remove file fan-xiaomi.js.gz in order for .js to be read, otherwise it uses old version.
NNow you can install from HACS 1.5.2-beta1, does that work?

**Comment by matsube11** [comment]
Hi @insajd 
Installing `v1.5.2-beta1` fixed the problem :)
Thanks both of you, I had to restart HA after installing `v1.5.2-beta1` to have it to work properly.

**Comment by insajd** [comment]
Glad to hear that! Closing this issue then. Released 1.5.2 with this fix.

**Comment by ikaruswill** [comment]
@matsube11 Nice! Thanks for reporting and working this out with us
