### ISSUE TITLE
Fan angle toggle: add 140°

### ISSUE THREAD

**Issue by iron91770** [ikaruswill/lovelace-fan-xiaomi#34]
Hello,

Is it possible to add the angle 140 ° in the oscillation angle?

thank you

**Comment by insajd** [comment]
I second this request 👍 

First we need to add 140 to dictionary in here https://github.com/syssi/xiaomi_fan/blob/8b0c1f034b82667fdec0c02e0238f0c7c528555b/custom_components/xiaomi_miio_fan/fan.py#L195
Secondly, change this card to support 140 angle.
Do all fans support 140 angle, or only some? @iron91770  which one do you have?
@ikaruswill does you fan support 140 angle from Mi Home?
My dmaker.fan.p5 does support 140.

**Comment by iron91770** [comment]
My fan is Xiaomi Mijia 1x DC SMART FLOOR FAN

**Comment by iron91770** [comment]
Mi Home support 140 angle

**Comment by insajd** [comment]
That's the same fan as mine, technical name is p5. Need some info on other fans before making changes.

**Comment by ikaruswill** [comment]
@insajd Hmm. Unfortunately no. My fan only has 30, 60, 90, 120. This will have to be model-specific logic it seems

**Comment by insajd** [comment]
140 degree is implemented, needs https://github.com/syssi/xiaomi_fan **develop** branch though. There's no release yet after 0.2.0.
