### ISSUE TITLE
unable to load on version 0.112.1

### ISSUE THREAD

**Issue by roy-pa** [ikaruswill/lovelace-fan-xiaomi#37]
After upgrading to 0.112.1 custom card is not loading and  showing in hacs as ‘Not loaded’ please guide

**Comment by insajd** [comment]
Card is loading fine for me on 0.112.1.

Do you still have this problem? 
If you have, what card version are you using? What's written in Console tab when you click Ctrl+Shift+I in Chrome?

**Comment by roy-pa** [comment]
thanks dear for the update, it got fixed by changing the custom path to /local/community/... instead of /custom_components/...

**Comment by roy-pa** [comment]
thanks for the support

**Comment by insajd** [comment]
Thanks for letting know the solution. Glad you made it work!
