### ISSUE TITLE
Formatting of lovelace config

### ISSUE THREAD

**Issue by Hoekeren** [ikaruswill/lovelace-fan-xiaomi#41]
The format of the data for lovelace is not correct. 

Yours: 
- entity: fan.entity_id
  name: Fan Name
  type: 'custom:fan-xiaomi'

The right way:

entity: fan.entity_id
name: Fan Name
type: 'custom:fan-xiaomi'

thank for the great work

**Comment by insajd** [comment]
You're right that in lovelace it's differently formatted. Thanks for pointing that out.
