### ISSUE TITLE
from Xiaomi Mi Smart Pedestal Fan Integration to Xiaomi Mi Air Purifier & Xiaomi Mi Air Humidifier Integration

### ISSUE THREAD

**Issue by maximatchev** [ikaruswill/lovelace-fan-xiaomi#44]
syssi made another integration of Pedestal Fan. 
All fan models moved from "Xiaomi Mi Smart Pedestal Fan Integration" to "Xiaomi Mi Air Purifier & Xiaomi Mi Air Humidifier Integration" (https://github.com/syssi/xiaomi_airpurifier).
There are some new fan models.

Can you change your lovelace card to this integration. Thank you

**Comment by insajd** [comment]
So there's official component, xiaomi_air_purifier, and xiaomi_fan. I would gladly move to official component if possible to have less dependencies. 🤔 Thanks for info!

**Comment by insajd** [comment]
I tried adding fan through official component - it doesn't support my fan.
Air purifier integration did work and I prefer this now to the original.
Thanks for the tip @maximatchev !

**Comment by insajd** [comment]
@maximatchev install latest 1.5.3, it contains all necessary fixes.
