### ISSUE TITLE
v1.5.2) calling services of Natural mode in Lovelace

### ISSUE THREAD

**Issue by YunsuChoi** [ikaruswill/lovelace-fan-xiaomi#46]
![notitle](https://user-images.githubusercontent.com/1073023/114985633-fc1a5300-9ecd-11eb-9f53-e9c57b61a66c.jpg)
{syssi's Xiaomi Mi Smart Pedestal Fan Integration version : 0.3.1
your's Xiaomi Smartmi Fan Card frontend version : 1.5.2}

Cannot call service natural mode on/off either from Lovelace UI 
I can call service in developer mode but not in your Lovelace custom frontend.

**Comment by craxo** [comment]
I have just recently set up my Smart Fan 2S, and I faced the same issue.
For me however it also applies to the child lock, angle and timer.

What I noticed is that this add-on is trying to call: 'fan/xiaomi_miio_set_natural_mode_on'
But the service is listed in the developer tool as  'xiaomi_miio_fan: fan_set_natural_mode_on'

**Comment by craxo** [comment]
This (https://github.com/syssi/xiaomi_fan/issues/108) issue for the component that this love-lace is worth mentioning. This love-lace is outdated in terms of using the old entityId's.

**Comment by ikaruswill** [comment]
Interesting. Thanks for the reference. Looks like an update is due here. 

I'll put up the PR soon, otherwise PRs are welcome!

**Comment by craxo** [comment]
It is thus stated that version v0.2.0 of the [Xiaomi Mi Smart pedestal Fan Integration](https://github.com/syssi/xiaomi_fan) is required, which works.
I would contribute with a PR but I have no experience with components / love-laces in HA. I tried to update the callService with the updated entityId from the component with no luck tho.

**Comment by insajd** [comment]
Check https://github.com/ikaruswill/lovelace-fan-xiaomi/releases/tag/1.5.3-beta2 this should fix service call names

**Comment by craxo** [comment]
I did the exact as what was provided with the 1.5.3-beta2 but to no avail. The services are still failing.

**Comment by insajd** [comment]
@craxo did you install it through HACS, or did changes manually?
If you have file fan-xiaomi.js.gz in the folder, then either remove it, or reinstall latest version using HACS.

Let me know if this helps or not.

**Comment by craxo** [comment]
Removed it entirely, and updated to the 1.5.3, good job! Does Home Assistant unzip that .gz every time, meaning any changes to the fan-xiaomi.js have no effect locally?

**Comment by insajd** [comment]
@craxo yes, when there's .gz file it sends that one instead of .js. That decreases the traffic 3 times in xiaomi-fan plugin case.
If you delete the .gz file, it sends the .js version.
