### ISSUE TITLE
Topics missing for repository in HACS

### ISSUE THREAD

**Issue by insajd** [ikaruswill/lovelace-fan-xiaomi#50]
Hi @ikaruswill , can you please add topics to the project? I am missing permissions for this it seems.
Values that I think should be added:
`fan`, `xiaomi`, `plugin`, `lovelace`, `custom-card`

https://docs.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics

**Comment by ikaruswill** [comment]
Alright, I've added the topics. Thanks for spotting this @insajd
