### ISSUE TITLE
Indecisive states on the card  when pressed

### ISSUE THREAD

**Issue by craxo** [ikaruswill/lovelace-fan-xiaomi#51]
States of the attributes on the card in the lovelace toggles back and forth when pressed, then settles on the new state.
I havent dug too deep, but I found this merge interesting: https://github.com/ikaruswill/lovelace-fan-xiaomi/pull/8

See [video](https://photos.app.goo.gl/EA3AforoxjDKWbhu9)

**Comment by insajd** [comment]
@craxo try https://github.com/ikaruswill/lovelace-fan-xiaomi/tree/insajd-disable_immediate_ui branch, and enable new config option.

**Comment by insajd** [comment]
No longer a problem that I see when `disable_immediate_UI: True` is set
