### ISSUE TITLE
Speed and Natural not working for mihome leshow.fan.ss4

### ISSUE THREAD

**Issue by deco3690** [ikaruswill/lovelace-fan-xiaomi#57]
On/Off and Oscillate are working. This fan does not have any child lock mode, 

However, Speed and Natural not working - will you be able to add? Thank you!

![ss4 2021-05-11 110618](https://user-images.githubusercontent.com/26707592/117752360-3535b100-b249-11eb-9c38-470ccdec6256.jpg)

**Comment by insajd** [comment]
Try latest 1.5.5 release. 
Angle, Child lock should disappear.
Natural mode button should start working.
Not sure why speed setting is not working though. Let me know how it goes.

**Comment by deco3690** [comment]
Wow that's fast, and nice, The Angle, Child lock no longer appear. Natural and speed still dont work though.

**Comment by deco3690** [comment]
You are right. Even though the options for Natural and Sleep appear on HA, the Mi Home app only shows a sleep option. They should be the same. The sleep mode does not have a high/low cycle like other xiaomi fans.

There isnt a fixed 3 or 4 modes like the zhimi.v3 fan, instead the IR control sets 1%(L or sleep), 100% (H). The IR control +/- increases and decreases by 11% (I dont know why it is 11% and not 10%). It gets noisy above 50%. 

If I were to pick 3 speeds, I would say 30% 60% 100%.  Yes, prob most logical for Button Nature to be be a separate speed setting for speed 1% and renamed to Sleep for leshow ss4 fan. 
![leshow ui_2021-05-12_11-55-42](https://user-images.githubusercontent.com/26707592/117916832-7ea20100-b31a-11eb-8915-acf8b7e619a0.jpg)

**Comment by insajd** [comment]
You can test https://raw.githubusercontent.com/ikaruswill/lovelace-fan-xiaomi/insajd-ss4/fan-xiaomi.js version, by overwriting /www/community/lovelace-fan-xiaomi/fan-xiaomi.js file, and deleting /www/community/lovelace-fan-xiaomi/fan-xiaomi.js.gz
You need to add to card config this to make it work currently, it should make card work with all unsupported fans.
```
    use_standard_speeds: true
```
* This makes fan use low/medium/high speeds that all fans in HA should support.
* Sleep mode button should set fan to speed 1, and disabling sleep mode should set fan to speed `low`

I will add preset speeds [11/33/55/77/100] later if set_percentage works for you fan, then you will be able to use fan without `use_standard_speeds` flag.

**Comment by insajd** [comment]
You can now just install 1.5.6-beta1 version, and enable `use_standard_speeds`

**Comment by deco3690** [comment]
Works well. Thanks!

**Comment by ikaruswill** [comment]
Closing issue, problem seems to be fixed for now with model-specific custom logic.
