### ISSUE TITLE
Only see fan speed and oscillation

### ISSUE THREAD

**Issue by Haasie** [ikaruswill/lovelace-fan-xiaomi#59]
Hello,

Since it is getting warmer in here (Netherlands) i plugged in my xiaomi fan 1C back in again.
in the past the card works like a charm but now i only see 3 parameters to adjust: power, speed (1,2,3) and oscillation.
<img width="952" alt="afbeelding" src="https://user-images.githubusercontent.com/45860400/120396595-1d78b680-c337-11eb-8ebb-64ecac6dd47d.png">
my config wor the card is like: 
<img width="332" alt="afbeelding" src="https://user-images.githubusercontent.com/45860400/120396639-35503a80-c337-11eb-9eb9-02915a6635e6.png">
and the config for the fan intself is:
![afbeelding](https://user-images.githubusercontent.com/45860400/120396722-5749bd00-c337-11eb-80f1-bb9577102ac8.png)

Am i doing somthing wrong?

**Comment by insajd** [comment]
What is missing is child lock and turn off timer. Oscillation angle is not supported by 1C right?

**Comment by insajd** [comment]
@Haasie check 1.5.6-beta2 version, it should support everything that 1C supports.

**Comment by Haasie** [comment]
I've installed the beta 2 version and still got the same card with only 2 buttons![image](https://user-images.githubusercontent.com/45860400/120497044-5f990b00-c3be-11eb-8d22-0f387c9a46f1.png)

**Comment by Haasie** [comment]
Angle is indeed not supported by the 1C

**Comment by insajd** [comment]
> I've installed the beta 2 version and still got the same card with only 2 buttons![image](https://user-images.githubusercontent.com/45860400/120497044-5f990b00-c3be-11eb-8d22-0f387c9a46f1.png)

Try refreshing the page with Ctrl+R combination. Old version is probably cached

**Comment by insajd** [comment]
Oh it's a phone.. try killing the app from the task manager probably

**Comment by Haasie** [comment]
Already killed it, restarted the HA server, cleard the frontend cache an tried it on my laptop. 

I use the xiaomi_miio_fan intergration in combination with the lovelace card.

**Comment by Haasie** [comment]
![image](https://user-images.githubusercontent.com/45860400/120501316-d1268880-c3c1-11eb-8b09-076cd7910994.png)
![image](https://user-images.githubusercontent.com/45860400/120501343-d4ba0f80-c3c1-11eb-9d73-3bccbf511cbb.png)

**Comment by insajd** [comment]
Could you remove the file www/community/lovelace-fan-xiaomi/fan-xiaomi.js.gz
and then also check that in file www/community/lovelace-fan-xiaomi/fan-xiaomi.js
There is `this.supportedAttributes.childLock = true;` written on line 59?
![image](https://user-images.githubusercontent.com/1233490/120504941-359b1500-c3cd-11eb-9a5d-9e7d7d82666e.png)

**Comment by Haasie** [comment]
I had to make the services myself. For now it works a littlebit ![image](https://user-images.githubusercontent.com/45860400/120695330-926cfd00-c4ab-11eb-9a5e-9947790c2bf7.png)

**Comment by Haasie** [comment]
Line 59 is as you showed in the screenshot above.

**Comment by insajd** [comment]
The card looks correct on your screenshot now. Did you change anything or the beta works?

**Comment by insajd** [comment]
And what do you mean " make the services myself" - where did you create which services?

**Comment by Haasie** [comment]
Like this ![image](https://user-images.githubusercontent.com/45860400/120715374-d02a4f80-c4c4-11eb-9a20-111878bb7144.png)

**Comment by insajd** [comment]
Thanks! But air purifiers should have fan_set_led_on / off service. Does it actually do something to pedestal fan 1C? This service doesn't do anything on my P5 fan.
Child lock should work on the card for you.

**Comment by Bastiencc** [comment]
Hi 
I also only have speed and oscillate on ma 1C. I tried 1.5.6-beta3, but nothing changed

**Comment by insajd** [comment]
> Hi
> I also only have speed and oscillate on mu 1C. I tried 1.5.6-beta3, but nothing changed

Could you please attach all attributes of the fan. If you have speed and oscilliation, that means you are missing timer and child lock, nothing else, right?

**Comment by Bastiencc** [comment]
yes I think so. maybe also "standar/night mode" (like in Mi Home apps) ?

![2021-06-11 16 15 47](https://user-images.githubusercontent.com/37021892/121700838-92cf4e80-cad0-11eb-804e-be5f7bb96843.jpg)


```
speed_list: off, low, medium, high, off, Level 1, Level 2, Level 3
preset_modes: off, Level 1, Level 2, Level 3
oscillating: true
speed: low
percentage: 33
percentage_step: 33.333333333333336
preset_mode: null
model: dmaker.fan.1c
angle: null
raw_speed: 1
delay_off_countdown: 0
ac_power: null
oscillate: true
direct_speed: null
natural_speed: null
child_lock: false
buzzer: false
led_brightness: null
use_time: null
temperature: null
humidity: null
battery: null
battery_charge: null
button_pressed: null
led: false
battery_state: null
mode: normal
friendly_name: Le ventilateur du bas
supported_features: 11
icon: mdi:fan
```

**Comment by insajd** [comment]
Night mode is simply speed 1, isn't it? It should be available if you turn on "Show sleep mode button" in the card settings.
![image](https://user-images.githubusercontent.com/1233490/121701188-52280300-cad9-11eb-8e2c-3d77e198ce32.png)
After installation of 1.5.6-beta3, did you click Ctrl+Shift+R (in Chrome) to reload?
Which version of HA are you using?
What's your card config?

**Comment by insajd** [comment]
@Bastiencc highlighting you by nick. Questions in my previous comment.

**Comment by Bastiencc** [comment]
```
  - entity: fan.ventilateur_bas
    name: Ventilateur du bas
    type: 'custom:fan-xiaomi'
    force_sleep_mode_support: true
    platform: xiaomi_miio_fan
```

HA version is 2021.6.3

![image](https://user-images.githubusercontent.com/37021892/121703373-0b370f00-cad3-11eb-83f2-ad9b0ad53494.png)

**Comment by Bastiencc** [comment]
Ok after 2 reboot and 4 cache reloading now it is ok... very sorry !

![image](https://user-images.githubusercontent.com/37021892/121703941-96180980-cad3-11eb-9f59-3e580a9953f4.png)

**Comment by insajd** [comment]
> Ok after 2 reboot and 4 cache reloading now it is ok... very sorry !
> 
> ![image](https://user-images.githubusercontent.com/37021892/121703941-96180980-cad3-11eb-9f59-3e580a9953f4.png)

Do Child Lock and Timer buttons work? Glad it works now!

**Comment by Bastiencc** [comment]
Yes everything is ok now! Thanks you !
It's ok on my computer but not on my phone yet, so it is really a cache issue... Seems that HA doest not manage it right. Need to clear HA apps cache manualy . Sorry !

**Comment by Bastiencc** [comment]
@insajd I checked again about night mode and it not just a level 1 like. It alternate between low and speed, and there is 3 level available. I also have a Fan 2S and it look like "natural mode"

**Comment by insajd** [comment]
> @insajd I checked again about night mode and it not just a level 1 like. It alternate between low and speed, and there is 3 level available. I also have a Fan 2S and it look like "natural mode"

ok, so 1c natual  = level 1 + natural mode on. i'll see what I can do about this.
did not get what you mean about level 3 though, 1c should have 3 levels on this card.

**Comment by Bastiencc** [comment]
Sorry for my english... Juste saying that there is 3 speed level available on night mode.

Like that:

![Screenshot_20210611-211010.jpg](https://user-images.githubusercontent.com/37021892/121737775-96c39680-caf9-11eb-834c-141f44d00223.jpg)

![Screenshot_20210611-211001.jpg](https://user-images.githubusercontent.com/37021892/121737784-9b884a80-caf9-11eb-8fa5-cc43ac1e8168.jpg)

**Comment by insajd** [comment]
> Sorry for my english... Juste saying that there is 3 speed level available on night mode.

Then I would think that it makes more sense to add "Natural" button for 1C, then you can iterate through speeds. 
Then if you want toy can still enable sleep button which would just set speed to 1. 
Do you agree?

**Comment by Bastiencc** [comment]
Yes I think like you, sleep mode on 1C is more or less the same as natural mode for 1S 👍

**Comment by insajd** [comment]
> Yes I think like you, sleep mode on 1C is more or less the same as natural mode for 1S 👍

Could you try latest release 1.5.6-beta4 and see if natural button appears and work for you?
You should be able to toggle natural mode, and iterate through speeds 1-3.

**Comment by Bastiencc** [comment]
That's perfect, thank you very much!

**Comment by insajd** [comment]
Closing this as 1.5.6 version should correctly work with 1C fan now. Thanks for all the feedback @Bastiencc !

**Comment by Bastiencc** [comment]
> Closing this as 1.5.6 version should correctly work with 1C fan now. Thanks for all the feedback @Bastiencc !

Thanks to you for the good works done!
