### ISSUE TITLE
[feature request]  Support zhimi.fan.fa1 please!

### ISSUE THREAD

**Issue by godisjerry** [ikaruswill/lovelace-fan-xiaomi#63]
I have a zhimi.fan.fa1 but many functions are not available, could you support zhimi.fan.fa1? Thanks

**Comment by insajd** [comment]
@godisjerry unfortunately we can't do anything before https://github.com/syssi/xiaomi_fan/issues/79 is resolved.
How much functionality do you get out of fa1 fan right now, using HA ui ? Can you change speeds?

**Comment by godisjerry** [comment]
@insajd the fuction is unavailable when I click Angle, Timer, Speed, Natural. In addition, I use fan.increase_speed in the execution service function to allow this device to adjust the fan speed normally.

**Comment by insajd** [comment]
> @insajd the fuction is unavailable when I click Angle, Timer, Speed, Natural. In addition, I use fan.increase_speed in the execution service function to allow this device to adjust the fan speed normally.

As I understand, only button ON is working, and also fan.increase_speed service is working. Right?
Based on these assumptions 1.5.7-beta3 is released - you'll have only ON/increase speed/decrease speed buttons.

When(if?) upstream adds proper fa1 fan support, we will get all other functionality working.

**Comment by ikaruswill** [comment]
Closing as rudimentary fa1 support has been implemented, though upstream has yet to implement fa1 support. Do reopen if you face further issues.
