### ISSUE TITLE
2021.9 will break this card

### ISSUE THREAD

**Issue by andriej** [ikaruswill/lovelace-fan-xiaomi#64]
There are changes (support of xiaomi fans natively) that will break this card, as there are new sensors

**Comment by insajd** [comment]
> There are changes (support of xiaomi fans natively) that will break this card, as there are new sensors

Thanks for information! Too bad I was away all this time. Will wait for release today and fix the card then.

**Comment by fribse** [comment]
For me, most of it works now, except the speed. I'm on HA 2021.11.2

**Comment by ikaruswill** [comment]
Closing issue as native support has already been implemented in 2.0.0
