### ISSUE TITLE
Speed button no longer works

### ISSUE THREAD

**Issue by vexorg3000** [ikaruswill/lovelace-fan-xiaomi#83]
when pressing the Speed button on the card the following error message is displayed:

"failed to call service fan/set_speed. Service not found"

Button also does not display the correct fan speed 
![fan card](https://user-images.githubusercontent.com/61636090/163658418-7c0527df-15f6-4f85-9fa3-ff3a4046e5fe.png)

**Comment by deco3690** [comment]
Same here. I am using zhimi.fan.v3 (xiaomi_miio / xiaomi_miio_airpurifier) and leshow.fan.ss4 (xiaomi_miio_airpurifier). On/off, natural, oscillate work, but speed does not work.

**Comment by ckholy2** [comment]
it is because home assistant 2022.4 removed fan/set_speed service.  developer has to change to use set_percentage

**Comment by vexorg3000** [comment]
ckholy2 is correct. 

I dont know how to change that code unfortunatly.

![image](https://user-images.githubusercontent.com/61636090/163982067-899240ee-52ca-4e8b-8b75-a6e12f0212c7.png)

**Comment by zslibra** [comment]
same here.
I'm using dmaker_fan_p9.

**Comment by ikaruswill** [comment]
Thanks for raising this, I'm currently overseas and will be back in a couple of days, seems like set_speed has finally been deprecated and removed. Will submit a fix for this when I get back.

**Comment by zslibra** [comment]
> Thanks for raising this, I'm currently overseas and will be back in a couple of days, seems like set_speed has finally been deprecated and removed. Will submit a fix for this when I get back.

Yes, set_speed has finally been deprecated and not found "speed" and "speed_list" in attributes after ha 2022.4.0.

**Comment by garv3** [comment]
Is there an update to this issue?

**Comment by Bastiencc** [comment]
Hi @ikaruswill did you find a fix ? Thanks !

**Comment by ikaruswill** [comment]
Just got back from overseas, will be working on it this week! (Unless
someone has an MR already)

I hadn't realized this prior because I'm still on an older version of HA.
Guess it's time to update as well.

**Comment by Bastiencc** [comment]
thanks you very much !

**Comment by ikaruswill** [comment]
Thanks for waiting. It's now fixed in [2.1.0](https://github.com/ikaruswill/lovelace-fan-xiaomi/releases/tag/2.1.0). Try it out and let me know if you face any issues!

**Comment by deco3690** [comment]
It's now working for my Xiaomi standing fan (zhimi V3) all buttons working, but not working for leshow bladeless tower fan (ss4) none of the buttons are working. What info can I help to collect?

**Comment by garv3** [comment]
The most important info should be a list of all entities that belong to the device including their default names and value types.

**Comment by deco3690** [comment]
With xiaomi_miio_fan , leshow.fan.ss4 has the following attributes. This fan cannot connect using xiaomi_miio.

preset_modes: Manual, Sleep, Strong, Natural
oscillating: true
percentage: 25
percentage_step: 1
preset_mode: Manual
model: leshow.fan.ss4
mode: 0
raw_speed: 25
buzzer: false
oscillate: true
delay_off_countdown: 0
error_detected: false
friendly_name: Fan Study
supported_features: 11
