### ISSUE TITLE
Failed to call service fan/set_speed

### ISSUE THREAD

**Issue by tsmanz** [ikaruswill/lovelace-fan-xiaomi#84]
It seems that fan.set_speed is no longer a supported service. fan.set_percentage works in automations for  Xiaomi fans so that may work as a replacement.

**Comment by garv3** [comment]
Yes, I've got the same issue!

**Comment by Bastiencc** [comment]
same issue here !

**Comment by DjDOESIT** [comment]
même problème

**Comment by ikaruswill** [comment]
Thanks for waiting. It's now fixed in [2.1.0](https://github.com/ikaruswill/lovelace-fan-xiaomi/releases/tag/2.1.0). Try it out and let me know if you face any issues!

**Comment by Bastiencc** [comment]
> Thanks for waiting. It's now fixed in [2.1.0](https://github.com/ikaruswill/lovelace-fan-xiaomi/releases/tag/2.1.0). Try it out and let me know if you face any issues! 

Thanks! But I still got this :
![Screenshot_20220521-144102__01.jpg](https://user-images.githubusercontent.com/37021892/169651950-d5e0a745-64b5-455a-81cf-d35a1f8b5894.jpg)

**Comment by ikaruswill** [comment]
@Bastiencc Can you do a force refresh? It's working as expected on my side. I'm using `2022.5.5`, using `zhimi.fan.za5`

**Comment by Bastiencc** [comment]
> @Bastiencc Can you do a force refresh? It's working as expected on my side. I'm using `2022.5.5`, using `zhimi.fan.za5`

yes , I had to remove the plugin and add it again. Now fan speed is ok, but sleep mode, natural mode, and oscilate are breaked. If I go back to previous version they are ok (but not fan speed, obviously)

**Comment by ikaruswill** [comment]
I see. Thanks for reporting @Bastiencc . Can I know your fan model code?

**Comment by Bastiencc** [comment]
it's ok with `zhimi.fan.sa1` 

![Uploading 2022-05-21 18.15.54.jpg…]()


but not with `dmaker.fan.1c`

![Uploading 2022-05-21 18.14.39.jpg…]()

**Comment by ikaruswill** [comment]
Thanks that's great information. Will take a look tomorrow and get back

**Comment by Bastiencc** [comment]
Thanks! Have a nice day

**Comment by ikaruswill** [comment]
Can you do a force refresh? It's working as expected on my side. I'm using
2022.5.5.
