### ISSUE TITLE
Natural mode button not working (Smart Mi 2s)

### ISSUE THREAD

**Issue by Lyr3x** [ikaruswill/lovelace-fan-xiaomi#88]
I just updated to `2.1.0` and it seems that the natural mode is broken. If the natural mode is `off` i can turn it `on` via the card, but the status is not reflected (always off). Turning the natural mode `off` is not working at all.
Calling the service directly is working fine. There is no error visible in the logs

**Comment by garv3** [comment]
Works with my Smartmi Standing Fan 3.

**Comment by yeyeoke** [comment]
Yeah I'm having the exact same issue with my fan. 

Only configuration that might impact this may be: 

platform: xiaomi_miio_fan

**Comment by jesryn** [comment]
SAme problem for me with a P15

**Comment by djsnho** [comment]
Exactly the same problem with model: "dmaker.fan.p18" (Xiaomi standing fan 2)

**Comment by ian-craig** [comment]
I believe this is now fixed on master. Hopefully we'll have a new build pushed soon but we have made major changes recently for a separate issue so may move a little more carefully for that.

It sounds like from this discussion the issue was only with status reporting, not actually toggling the fan mode, but I noticed that when we set the preset mode we're using "Nature" or "Natural" as well. I tested "nature" on my device (which reports "Nature" as status) and it did not work, so I'm wondering whether any devices which report "nature" would still fail on the set.

**Comment by jesryn** [comment]
For me, the Smart Standing Fan Pro/P15 show the same status for Direct/Natural all the time. Natural is deselected, which means direct breeze. And it is not possible to toggle by clicking it. Nothing changes, no matter if the fan is set to direct or natural mode.

**Comment by ian-craig** [comment]
Interesting. @jesryn would you mind sharing the full state and attributes for your fan from the `Developer Tools > State` page? Both with nature mode on and off would be helpful so we can see what attribues and values are available to watch.

And just to confirm you're using the [Xiaomi Mi Smart Pedestal Fan](https://github.com/syssi/xiaomi_fan) integration not the default?

Also as a side note: It looks like P15 support through the native/default integration is coming soon so will hopefully also resolve this for you https://github.com/home-assistant/core/issues/73496

**Comment by jesryn** [comment]
@ian-craig Sorry for my late answer. Yes I use Xiaomi Mi Smart Pedestal Fan and use it in config with I use it with "platform: xiaomi_miio_fan". It looks like this under developers tools:


preset_modes: off, Level 1, Level 2, Level 3, Level 4 
direction: null 
oscillating: true 
percentage: 100 
percentage_step: 1 
preset_mode: Level 4 
model: dmaker.fan.p15 
angle: 60 
raw_speed: 100 
delay_off_countdown: 0 
ac_power: null 
oscillate: true 
direct_speed: null 
natural_speed: null 
child_lock: false 
buzzer: false 
led_brightness: null 
use_time: null 
temperature: null 
humidity: null 
battery: null 
battery_charge: null 
button_pressed: null 
led: false 
battery_state: null 
mode: nature 
friendly_name: Fläkt TV-rummet 
supported_features: 15
--

**Comment by ikaruswill** [comment]
Fixed in 2.2.0, thanks for waiting, please do reopen this if you still face this issue.

**Comment by Lyr3x** [comment]
@ikaruswill still not working for me. The button is not reactive at all and also does not create a error message. I reinstalled the component. Anything else?
